Step Inititialization
bitrise-steplib/steps-expo-detach pull request #2
Opened 2018-09-14 11:14 UTC by BirmacherAkos

## Basics
This step uses the [expo-cli](https://docs.expo.io/versions/latest/introduction/installation#local-development-tool-expo-cli) to create Xcode and Android Studio projects for your app.

## Eject Method
- If you use any Expo SDK you must to provide username and password for your Expo account.
Because in this case, the expo-cli will use the expoKit eject method which needs an account.

- If your project does not import any Expo SDK then you should not use the username/password option.
Because in this case, the expo-cli will use the plain eject method.

2018-09-19 14:27 UTC, BirmacherAkos commented on main.go
> +	log.Infof("Loging out from Expo")
Logging out

2018-09-19 14:28 UTC, BirmacherAkos commented on step.yml
> +        Your password for your for `https://expo.io/` .
typo

2018-09-20 08:40 UTC, trapacska requested changes

2018-09-20 08:40 UTC, trapacska commented on README.md
> +# [Beta] Expo Detach
please copy-paste the release guide at the end

2018-09-20 08:40 UTC, trapacska commented on bitrise.yml
> +  - BITRISE_STEP_ID: expo-detach
these are not required because of the new release flow

2018-09-20 08:40 UTC, trapacska commented on bitrise.yml
> +  - BITRISE_STEP_ID: expo-detach
also, instead collect secrets here like: USER_NAME

2018-09-20 08:40 UTC, trapacska commented on expo/expo.go
> +func New(version string, method EjectMethod) *Expo {
it shall not be a pointer -> *Expo

2018-09-20 08:40 UTC, trapacska commented on expo/expo.go
> +	log.Printf("$ " + cmd.PrintableCommandArgs())
this is a package, it shall not have hardcoded logging. please use logger to be able to disable/enable logging, or simply just return with the command and do the logging/running from main scope

2018-09-20 08:40 UTC, trapacska commented on expo/expo.go
> +	log.Printf("$ " + cmd.PrintableCommandArgs())
as far as I can see, almost all the functions is about to run commands. I think these functionalities are should not be a package but a well separated and managed main codebase.

2018-09-20 08:40 UTC, trapacska commented on main.go
> +	Logout         bool            `env:"logout,opt[true,false]"`
I think logout is necessary. It should not be optional. Also I would do it in defer just in case we log the user out properly.

2018-09-20 08:40 UTC, trapacska commented on main.go
> +	log.Infof("Loging out from Expo")
good catch

2018-09-20 08:40 UTC, trapacska commented on step.yml
> +
please remove unused newlines

2018-09-20 08:40 UTC, trapacska commented on step.yml
> +        Your password for your for `https://expo.io/` .
good catch

2018-09-24 09:13 UTC, trapacska approved these changes

2018-09-24 09:33 UTC, merged